### ISSUE TITLE
how to install mmcv and mmdet

### ISSUE THREAD

**Issue by GaroneHuang** [whai362/AE_TextSpotter#1]
@whai362 

After I installed mmcv and mmdet with pip which the commands were:

pip install mmcv-full==latest+torch1.6.0+cu102 -f https://download.openmmlab.com/mmcv/dist/index.html
pip install mmdet

I ran the command: bash tools/rects_dist_train.sh local_configs/rects_ae_textspotter_r50_1x.py 8

but it reported the following error:

Traceback (most recent call last):
  File "tools/rects_train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
ImportError: cannot import name 'init_dist' from 'mmdet.apis' (/home/garone/anaconda3/lib/python3.8/site-packages/mmdet/apis/__init__.py)
Traceback (most recent call last):
  File "tools/rects_train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
ImportError: cannot import name 'init_dist' from 'mmdet.apis' (/home/garone/anaconda3/lib/python3.8/site-packages/mmdet/apis/__init__.py)
Traceback (most recent call last):
  File "tools/rects_train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
ImportError: cannot import name 'init_dist' from 'mmdet.apis' (/home/garone/anaconda3/lib/python3.8/site-packages/mmdet/apis/__init__.py)
Traceback (most recent call last):
  File "tools/rects_train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
ImportError: cannot import name 'init_dist' from 'mmdet.apis' (/home/garone/anaconda3/lib/python3.8/site-packages/mmdet/apis/__init__.py)
Traceback (most recent call last):
  File "tools/rects_train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
ImportError: cannot import name 'init_dist' from 'mmdet.apis' (/home/garone/anaconda3/lib/python3.8/site-packages/mmdet/apis/__init__.py)
Traceback (most recent call last):
  File "tools/rects_train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
ImportError: cannot import name 'init_dist' from 'mmdet.apis' (/home/garone/anaconda3/lib/python3.8/site-packages/mmdet/apis/__init__.py)
Traceback (most recent call last):
  File "tools/rects_train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
ImportError: cannot import name 'init_dist' from 'mmdet.apis' (/home/garone/anaconda3/lib/python3.8/site-packages/mmdet/apis/__init__.py)
Traceback (most recent call last):
  File "tools/rects_train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
ImportError: cannot import name 'init_dist' from 'mmdet.apis' (/home/garone/anaconda3/lib/python3.8/site-packages/mmdet/apis/__init__.py)
Traceback (most recent call last):
  File "/home/garone/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/garone/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/garone/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/garone/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/garone/anaconda3/bin/python', '-u', 'tools/rects_train.py', '--local_rank=7', 'local_configs/rects_ae_textspotter_r50_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

I want to know how to install mmcv and mmdet correctly so that I can run it. Thanks!

**Comment by whai362** [comment]
https://github.com/open-mmlab/mmdetection/blob/v1.0rc0/INSTALL.md

**Comment by whai362** [comment]
pip install mmcv==0.2.13 --user

**Comment by GaroneHuang** [comment]
It can't install mmcv with this method


    ERROR: Command errored out with exit status 1:
     command: /home/garone/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rszl7l43/mmcv/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rszl7l43/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-u6vi5a39
         cwd: /tmp/pip-install-rszl7l43/mmcv/
    Complete output (33 lines):
    WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
    ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
    ERROR: No matching distribution found for pytest-runner
    Traceback (most recent call last):
      File "/home/garone/anaconda3/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/home/garone/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/garone/anaconda3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp20h4pvq2', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rszl7l43/mmcv/setup.py", line 55, in <module>
        setup(
      File "/home/garone/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "/home/garone/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/garone/anaconda3/lib/python3.8/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/garone/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "/home/garone/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/home/garone/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/home/garone/anaconda3/lib/python3.8/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/garone/anaconda3/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/home/garone/anaconda3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp20h4pvq2', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
