### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'

### ISSUE THREAD

**Issue by mxin262** [whai362/AE_TextSpotter#2]
你好，我按照你的环境配置好了。但是运行下面这句时
tools/rects_dist_train.sh local_configs/rects_ae_textspotter_r50_1x.py 8

出现以下错误，请问可以是什么问题呢？安装的mmcv和mmdet的版本是你给出的版本。

Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'
2020-10-17 15:51:29,024 - INFO - Distributed training: True
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/mmcv/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'
Traceback (most recent call last):
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/my/anaconda3/envs/AE-1.6/bin/python', '-u', 'tools/rects_train.py', '--local_rank=0', 'local_configs/rects_ae_textspotter_r50_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by whai362** [comment]
I have fixed this bug in the latest commit. Thank you very much.

**Comment by mxin262** [comment]
@whai362 你好，我使用了你最新更新的代码后，还是会报错，运行下面这句时，出现以下错误，请问这是什么问题？
tools/rects_dist_train.sh local_configs/rects_ae_textspotter_r50_1x.py 8

Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/utils/registry.py", line 67, in build_from_cfg
    obj_type, registry.name))
KeyError: 'None is not in the detector registry'
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/utils/registry.py", line 67, in build_from_cfg
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    obj_type, registry.name))
KeyError: 'None is not in the detector registry'
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/utils/registry.py", line 67, in build_from_cfg
    obj_type, registry.name))
KeyError: 'None is not in the detector registry'
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/utils/registry.py", line 67, in build_from_cfg
    obj_type, registry.name))
KeyError: 'None is not in the detector registry'
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 43, in build_detector
    main()
  File "tools/rects_train.py", line 84, in main
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 15, in build
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 43, in build_detector
    return build_from_cfg(cfg, registry, default_args)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/utils/registry.py", line 67, in build_from_cfg
    obj_type, registry.name))
KeyError: 'None is not in the detector registry'
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/utils/registry.py", line 67, in build_from_cfg
    obj_type, registry.name))
KeyError: 'None is not in the detector registry'
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/utils/registry.py", line 67, in build_from_cfg
    obj_type, registry.name))
KeyError: 'None is not in the detector registry'
2020-10-18 09:41:56,640 - INFO - Distributed training: True
Traceback (most recent call last):
  File "tools/rects_train.py", line 108, in <module>
    main()
  File "tools/rects_train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/media/my/e694bdda-b2a9-4fc1-97dd-1cf7547cab1e/AE_TextSpotter/mmdetection-1.0rc0/mmdet/utils/registry.py", line 67, in build_from_cfg
    obj_type, registry.name))
KeyError: 'None is not in the detector registry'
Traceback (most recent call last):
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/my/anaconda3/envs/AE-1.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/my/anaconda3/envs/AE-1.6/bin/python', '-u', 'tools/rects_train.py', '--local_rank=0', 'local_configs/rects_ae_textspotter_r50_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by whai362** [comment]
不清楚，有可能是环境的问题。请确保你的环境可以训练mmdet1.0。

**Comment by mxin262** [comment]
Thanks. I can run it now
