### ISSUE TITLE
ReCTSDataset is not in the dataset registry

### ISSUE THREAD

**Issue by ulanbator** [whai362/AE_TextSpotter#4]
测试代码报错：
KeyError: 'ReCTSDataset is not in the dataset registry'
Traceback (most recent call last):
  File "tools/rects_test.py", line 276, in <module>
    main()
  File "tools/rects_test.py", line 243, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/fangzheng/iflytek_project/AE_TextSpotter/mmdetection/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/fangzheng/anaconda3/envs/AET/lib/python3.6/site-packages/mmcv/utils/registry.py", line 164, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'ReCTSDataset is not in the dataset registry'

data目录已经上传数据集了，请问还要执行什么操作吗？

**Comment by whai362** [comment]
我这边没有出现这个问题，能正常训。
或许是https://github.com/whai362/AE_TextSpotter/blob/main/mmdet/datasets/__init__.py 里面的问题，我修改了一下，你看看能不能跑呢？
正常跑起来是这样的。
![image](https://user-images.githubusercontent.com/8529570/96959724-47f9ca00-1533-11eb-977f-abdf9d0edf22.png)

**Comment by ulanbator** [comment]
我是用下载的权重去测试集测试的
命令：tools/rects_dist_test.sh local_configs/rects_ae_textspotter_lm_r50_1x.py work_dirs/rects_ae_textspotter_lm_r50_1x/latest.pth 8 --json_out results.json
然后更新了代码，结果还是报上面的错误
