### ISSUE TITLE
KeyError: 'AE_TextSpotter is not in the detector registry'

### ISSUE THREAD

**Issue by EuphoriaYan** [whai362/AE_TextSpotter#7]
各项环境都按照您的说明中的装好了，不太相同的是，我是自己下了份mmdet，然后git checkout到1.0rc1，再install的；最后再把各项build出来的mmdet目录放回您项目的mmdet目录中，并重新加上poly_nms,Albu,ReCTSDataset等您项目独有的类，修改各个__init__.py等等；
目前能正常使用您的预训练模型进行测试，但在尝试训练时出现了报错：
```
Traceback (most recent call last):
  File "tools/rects_train.py", line 109, in <module>
    main()
  File "tools/rects_train.py", line 85, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/euphoria/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/euphoria/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/euphoria/mmdetection/mmdet/utils/registry.py", line 67, in build_from_cfg
    obj_type, registry.name))
KeyError: 'AE_TextSpotter is not in the detector registry'
```
请问这个错误是由于没有在您项目下的mmdet里build造成的吗？我查看了项目下的`mmdet/models/detectors/__init__.py`，其中有`from .ae_textspotter import AE_TextSpotter`，`__all__`中也有AE_TextSpotter，所以我猜测是否是因为这个register是在build mmdet的时候已经做了？

**Comment by EuphoriaYan** [comment]
贴一个目前的`detectors/__init__.py`

```
from .base import BaseDetector
from .cascade_rcnn import CascadeRCNN
from .double_head_rcnn import DoubleHeadRCNN
from .fast_rcnn import FastRCNN
from .faster_rcnn import FasterRCNN
from .fcos import FCOS
from .fovea import FOVEA
from .grid_rcnn import GridRCNN
from .htc import HybridTaskCascade
from .mask_rcnn import MaskRCNN
from .mask_scoring_rcnn import MaskScoringRCNN
from .reppoints_detector import RepPointsDetector
from .retinanet import RetinaNet
from .rpn import RPN
from .single_stage import SingleStageDetector
from .two_stage import TwoStageDetector
from .ae_textspotter import AE_TextSpotter

__all__ = [
    'BaseDetector', 'SingleStageDetector', 'TwoStageDetector', 'RPN',
    'FastRCNN', 'FasterRCNN', 'MaskRCNN', 'CascadeRCNN', 'HybridTaskCascade',
    'DoubleHeadRCNN', 'RetinaNet', 'FCOS', 'GridRCNN', 'MaskScoringRCNN',
    'RepPointsDetector', 'AE_TextSpotter', 'FOVEA'
]
```

**Comment by EuphoriaYan** [comment]
自行直接在您的项目里build后解决了问题
